### PR TITLE
Upgraded to Rails 7

### LINKED ISSUE #9: We need to upgrade this repo to Rails 7 first
Given that this repo is a dependency of all other neeto repos, we'd have to first upgrade this repo to Rails 7.

@Anamika-123 _a

Can you please take this up with the highest priority? In order to understand the file changes please go through:
- The wheel PR: https://github.com/bigbinary/wheel/pull/784 and this comment: https://github.com/bigbinary/wheel/pull/784#issuecomment-1043994549

cc: @unnitallman

### PR DESCRIPTION
**Pull request by yedhink**
Fixes #9 

@unnitallman _a I am not sure how I should be debugging this PR locally. Should I install the gem locally and use it in another project or is there a way to test whether this gem is working with the upgrade? Can you please review? Thanks.

**We need to have a call before merging this PR because we will have to merge the wheel PR in parallel to this one.**

### CODE REVIEW

**Comment by unnitallman** [comment]
@Anamika-123 _a

**Comment by Anamika-123** [comment]
@yedhink Is there any app that's working on Rails 7?

**Comment by Anamika-123** [comment]
@yedhink I tried testing the gem locally on [bigbinary/wheel#784](https://github.com/bigbinary/wheel/pull/784) and its working fine.

Screenshot 2022-02-18 at 10 39 40 PM

I will test it on neeto apps as well. Let me know when you upgrade any of the apps.

**Comment by neerajdotname** [comment]
@yedhink @unnitallman Let's test on neetoEngage.

1. Disable neeto-compliance.
2. Upgrade neetoEngage to Rails 7.
3. Use area51
4. Test and ensure things are working
5. We will do the same for one more product say "Runner" and then we can add to compliance for everyone to upgrade to Rails 7. 
6. Enable neeto-compliance

**Comment by neerajdotname** [comment]
@yedhink @unnitallman @Anamika-123 How did we get entangled with Rails 7 https://www.loom.com/share/48105fc1478343739170c44005df6ad6

**Comment by chiraggshah** [comment]
I am not sure why we need to upgrade area51 to Rails 7. 
area51 is an engine and shouldn't be locked to a specific version of rails. It should use whatever version the parent/host application is using.

I think the issue is because we have locked the version of rails for area51 to be [6.1.4.1](https://github.com/bigbinary/neeto-area51/blob/master/neeto-area51.gemspec#L25), which should not be the case. We should remove that line.
Refer https://guides.rubyonrails.org/engines.html#other-gem-dependencies

That should remove the dependency of the engine on a specific rails version and unblock the host application to upgrade to any version of rails.

cc @yedhink @unnitallman

**Comment by chiraggshah** [comment]
@neerajdotname : I have tried to explain the question you posted in the above loom video : https://www.loom.com/share/44cd326a31fb4b569f74bb1483756595

@yedhink @unnitallman Please add on if I have missed anything.

**Comment by yedhink** [comment]
The main reasons for upgrading to Rails 7 was that we should slowly move away from Webpacker ecosystem to `esbuild` compilation given that [Webpacker is slowly dying](https://github.com/rails/webpacker#webpacker-has-been-retired-). That upgrade might require some structural changes starting from Wheel itself.

More than that, security fixes, bug fixes, lots of deprecations, new features(like `async query executor`, native `encrypts` in activerecord, retry activejobs unlimitedly) etc were the factors that initiated the push to Rails 7.

It's a major upgrade. Thus it will involve updates in most of the BigBinary maintained gems as well as neeto repo specific changes too.

>So unless upgrading wheel to Rails 7 is a must for a specific reason let's not talk about Rails 7 for a while.

Currently, there aren't any blocker kind of reasons that lead to upgrading. But I feel this upgrade is something that we ought to take up before CH2022 batch arrives in BB. Because LRRB ought to be up to date with the latest practices in Rails as well as Ruby community in my opinion.

@neerajdotname We will currently put all Rails 7 upgrades on hold as mentioned in https://github.com/bigbinary/neeto-area51/pull/11#issuecomment-1045288713.

**Comment by unnitallman** [comment]
> So it seems we took it upon yourself to upgrade wheel to Rails 7. If it is not a necessity then let's not worry about upgrading wheel to Rails 7 for a few months. Here is why.
> 
> 1. Lots of neeto products have issues with all kinds of stability. From React to emails to Rails etc.
> 2. Prebooting heroku is much more of a issue because sometimes when production is deployed then heroku alert is saying that the site was down. So we need to take a look at prebooting.
> 3. The whole incineration thing is not fully baked
> 4. There are other things we have to worry about.
> 
> So unless upgrading wheel to Rails 7 is a must for a specific reason let's not talk about Rails 7 for a while.

@neerajdotname 

1. Preboot I think is a solved issue, we will know for sure this week, I have enabled it on all the production apps. I believe we won't have deployment related downtimes anymore. 
2. Incineration - That needs work, I would need 1 person to work with me and I can take this up. 
3. "neeto products have issues with all kinds of stability. From React to emails to Rails etc." - Would be helpful to have more specific inputs on this one, the way I see it, I haven't noticed that much of issues. But if there are, we could list it out and sort it out soon.

My case for upgrading to Rails 7 soon:

1. Performance and security upgrades as Yedhin pointed out.
2. Since it is a major upgrade, chance of minor breakages is there. So I think its safer to do it at this stage than waiting for real customers to be onboard.

I believe we could complete the upgrades in a week, should be easy once we get Chat, Form, Desk and KB migrated.

**Comment by chiraggshah** [comment]
Agree on the above too. Especially because webpacker is dying and it would be great if we could get rid of it sooner rather than later.

With https://github.com/bigbinary/neeto-area51/pull/12 merged which removes the rails version dependency, it should also not be a blocker.

**Comment by shreyansh-g24** [comment]
@yedhink @Anamika-123 Please merge the PR if it looks good. I'll pick up upgrading neeto-area51 to rails 7 following this.

**Comment by yedhink** [comment]
@shreyansh-g24 We can't merge this until we get a confirmation from Neeraj https://github.com/bigbinary/neeto-area51/pull/11#issuecomment-1045288713 on whether we should upgrade to Rails 7 now.

**Comment by neerajdotname** [comment]
@yedhink @chiraggshah @unnitallman I had no idea that webpacker was dying so fast and there was such an urgency of it. I wanted to delay it but let's do it now. However we need to more methodical that it seems we are. We can't mix two things. Area51 working and Rails upgrade are two separate things.

My suggestion would be to make features work towards the release. @unnitallman I randomly click on links and I keep getting error messages or things happen that is not expected. That's what I mean by the stability issue.

I believe by the end of the this week things should be in a better state. Starting next week ( Feb 28) number of bugs should be low enough that folks should start working on features. I think that's a good time to work on this.

Let me know if anyone has any questions.

**Comment by neerajdotname** [comment]
We need to plan from ground up how to upgrade to Rails 7. Closing this issue.

**Pull request closed without merging**
