### PR TITLE
Setup links resources

### LINKED ISSUE #48: Setup links resources
Links
  - name
  - url

routes:
  -  /area51/links - index

### PR DESCRIPTION
**Pull request by shreyansh-g24**
FIXES #48

### CODE REVIEW

**Comment by neerajdotname** [comment]
@shreyansh-g24 https://www.loom.com/share/891a01f0b21d4f929abaec9bc3f2cf7a

**Comment by shreyansh-g24** [comment]
@shreyansh-g24 _a

**Comment by shreyansh-g24** [comment]
@unnitallman _a

**Comment by shreyansh-g24** [comment]
Screenshot 2022-04-18 at 11 09 31 AM
Dropdown has been added for links actions. Please check. @unnitallman _a

**Comment by shreyansh-g24** [comment]
@unnitallman  https://www.loom.com/share/54ce4faca61244e9abcd5a0f7a495bc0
Please recommend if we should change the UI / any feature.
cc // @neerajdotname @karthiknmenon

**Comment by neerajdotname** [comment]
@shreyansh-g24 This is looking good. As discussed in the chat next task would be to not to do perform least amount of KPI extraction task in ruby. Can you point me to the code where the KPI values are being retrieved in say chat.

**Comment by shreyansh-g24** [comment]
@unnitallman _a

**Pull request merged**
